### ISSUE TITLE
Incorrect Segment Mask

### ISSUE THREAD

**Issue by wolfwubo** [hsysfan/YOLOv5_Segmenation_implement#1]
Hi, hysfan
I use windows10 with pytorch 2.0 + cuda11.8 + cudnn 8.8 + microsoft.ml.onnxruntime v1.14.1 + opencvsharp 4.7, and convert my retrained weight file with command: python export.py --weights yolov5s_seg_best.pt --include onnx --opset=12 --imgsz 512 --device 0. Also change the c# project  code NamedOnnxValue.CreateFromTensor("input", input) to NamedOnnxValue.CreateFromTensor("images", input) . Compile passed but the predict result seems incorrect. I guess it's probably caused by the different output of the Onnx network. Could you share the building environment including pytorch version，cuda version etc.  Thanks a lot.

# python predict.py --weights yolov5s_seg_best.onnx --source B_YP_2023_02_25_18_01_39_697_04_02832_03856_EM.png --imgsz 512：

![11](https://user-images.githubusercontent.com/75106343/233253200-382d3ea7-2a56-40ed-bed7-618cd9f20d5b.png)

# CSharp output:
![csharp](https://user-images.githubusercontent.com/75106343/233253396-81d070a5-1ccb-4ba5-8604-0fed5b7104b5.PNG)

**Comment by hsysfan** [comment]
Hello!, my code doesn't make perfectly same result with yolov5-seg because i dont add my code for deleting background except detected object i will commit soon maybe today or tomorrow. if i change my code i will answer here again. thank you

**Comment by wolfwubo** [comment]
Got it. Thanks for your prompt reply.

**Comment by hsysfan** [comment]
Hello again Wolf!, i changed My code now. i am newbie on github so could you check objectSegementation and mask2segments function YoloDetector.cs ?

https://github.com/hsysfan/YOLOv5_Segmenation_implement/blob/bdf6ecbd55a16977e26d2e538d814458dccf3788/OnnxSample/Yolov5/YoloDetector.cs#L309
https://github.com/hsysfan/YOLOv5_Segmenation_implement/blob/bdf6ecbd55a16977e26d2e538d814458dccf3788/OnnxSample/Yolov5/YoloDetector.cs#L413

**Comment by wolfwubo** [comment]
Hi hsysfan,

After checkout your new commit , it got an exception throws by OpenCVSharp: 
"0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols"

# Exception snapshot
![opencvsharp_exp](https://user-images.githubusercontent.com/75106343/233291378-935ddad6-a01b-427c-b6a7-f5467bfa7b8b.PNG)

# My test code( only include files i have modified to adapt 512 pixel image) & onnx model & test image:
[My_Code.zip](https://github.com/hsysfan/YOLOv5_Segmenation_implement/files/11283556/My_Code.zip)

I can provide any more information if needed.
THANKS again:)

**Comment by hsysfan** [comment]
Hello! i checked my code got a bug in calculate Xmin, Xmax, Ymin, Ymax
Then i changed my code now
Check it and Thanks for your questions

https://github.com/hsysfan/YOLOv5_Segmenation_implement/blob/22b5ed3f15e1deff40a3cffde21e0881643dda36/OnnxSample/Yolov5/YoloDetector.cs#L242-L266

**Comment by wolfwubo** [comment]
Hi, it works! Thanks for your effort & contribution. I'll close this issue and do further more test:)
