### ISSUE TITLE
Segmentation Label Question

### ISSUE THREAD

**Issue by wolfwubo** [hsysfan/YOLOv5_Segmenation_implement#3]
Hi,
Consider making the issue list clearly, i raised this new issue about the segmentation label:)
My dataset includes five labels, {0: 'DK', 1: 'LK', 2: 'CR', 3: 'EM', 4: 'BS'}
![Label](https://user-images.githubusercontent.com/75106343/233406269-8d94ac31-de04-42ac-b12a-a72b305b82c1.PNG)

But objectSegmentation returns some strange label IDs, what does these IDs mean? How to map the these IDs to the actual labeled IDs?
![1682003328237](https://user-images.githubusercontent.com/75106343/233408846-86db5f27-7797-4b38-84f9-313fcf7e7f0c.png)

**Comment by hsysfan** [comment]
I will check it soon but maybe i will work on weekend for my project.
It can be late sorry

**Comment by wolfwubo** [comment]
It's fine. Thank you for taking the time to deal with this issue, i really appreciate your help:)

**Comment by wolfwubo** [comment]
Hello, 
Maybe I have found the root cause of this issue:)
Please help to review below code when you are available. Thanks.
Define a new function named GetSegmentationMatrix( refer to GetDetectionMatrix ) for segmentation scenario. 

        public static List<List<float>> GetSegmentationMatrix(List<List<float>> candidate, int nc, 
            float pred_thresh = 0.25f, int max_nms = 30000)
        {
            var mat = new List<List<float>>();
            for (int i = 0; i < candidate.Count; i++)
            {
                if (candidate[i][4] < pred_thresh)
                {
                    // confidence less than threshold
                    continue;
                }

                int cls = -1;
                float max_score = float.MinValue;

                int nc_index_max = 5 + nc;
                for (int j = 5; j < nc_index_max; j++)
                {
                    // find the max score
                    if (candidate[i][j] > max_score)
                    {
                        cls = j;
                        max_score = candidate[i][j];
                    }
                }

                if (cls < 0) continue;

                List<float> tmpDetect = new List<float>();
                for (int j = 0; j < 4; j++) tmpDetect.Add(candidate[i][j]); //box
                tmpDetect.Add(candidate[i][cls]);   //class prob
                tmpDetect.Add(cls - 5);             //class
                mat.Add(tmpDetect);
            }

            //max_nms sort
            mat.Sort((a, b) => (a[4] > b[4]) ? -1 : 1);

            if (mat.Count > max_nms)
            {
                mat.RemoveRange(max_nms, mat.Count - max_nms);
            }
            return mat;
        }

Where argument nc is Number of Class.
![1682262472853](https://user-images.githubusercontent.com/75106343/233847714-43b49335-33c4-45f0-b7c5-9cf19ff4c56c.png)

Debug Watch
![image](https://user-images.githubusercontent.com/75106343/233848177-7630a511-f42b-4f3b-ae3d-9090bedaa14a.png)

Yolov5 Inference Result
![Image_640_Infer](https://user-images.githubusercontent.com/75106343/233848211-7838100e-0b56-4e74-a493-58451925c2d6.png)

**Comment by hsysfan** [comment]
Sorry for late 
I was so busy on weekend!
Thanks for correcting my error code
I will add you to contributor and check the code on my code
Thanks!

**Comment by hsysfan** [comment]
I thought maybe it was problem of start point of prediction's data
your code looks like the answer i think
if you dont mind, i want to add you in this repository as collaborator
thanks for your debugging!

**Comment by wolfwubo** [comment]
Okay. I'm very glad to be as a collaborator. Thank you for having me.
I will close this issue, and continue debugging, if any problem will let you know.
